zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    ref-data-service:
      path: /ref-data-service/**
      serviceId: REF-DATA-SERVICE
    notification-service:
      path: /notification-service/**
      serviceId: NOTIFICATION-SERVICE
    trade-data-service:
      path: /trade-data-service/**
      serviceId: TRADE-DATA-SERVICE
    metal-price-service:
      path: /metal-price-service/**
      serviceId: METAL-PRICE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost

server:
  host: localhost
  port: 8079

spring:
  application:
    name: zuul-api-service
    
ref-data-service:
  ribbon:
    eureka:
      enabled: true
    ReadTimeout: 30000
    ConnectTimeout: 30000

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000